### ISSUE TITLE
Converge on template best practices

### ISSUE THREAD

**Issue by milesfrain** [purescript-halogen/purescript-halogen-template#24]
Now that this template is updated to V5, I'd like to deprecate this other template to consolidate maintenance efforts:
https://github.com/purescript-templates/halogen/

What workflow should we suggest to new users? Parcel (featured in the other template) seems like a more beginner friendly option than webpack, and it includes automatic page refresh. With this template, a tool like `live-server` is required.

**Comment by garyb** [comment]
@thomashoneyman suggested switching to Parcel also I think. I only resisted it because I've never used it and don't really intend to in the foreseeable future either - not that I specifically have a problem with it or anything, it's just webpack works well enough for me and I don't like having to learn new tools every year or two when they're not necessarily that much better than their predecessor, just different.

Rant over :wink:. If the two of you think we really should though, go ahead.

**Comment by thomashoneyman** [comment]
@garyb I suggested Parcel for the template because, in my experience, it provides a much better zero-config experience than Webpack does. For a template this seems like a nice advantage. I suspect any user who wants to continue on to a full application can easily throw out Parcel in favor of another bundler if they really want to.

I don't have a _strong_ opinion on the matter -- any bundler will do, really -- but Parcel is particularly nice for such a small project like this one.

**Comment by thomashoneyman** [comment]
@milesfrain If you have ideas to make this template more ergonomic -- I saw the other template has live reload and optimized bundles out of the box -- without making it too much more complicated, I welcome a PR!
